[package]
name = "node-executor"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2018"

[dependencies]
trie-root = "0.12"
parity-codec = "3.3"
runtime_io = { package = "sr-io", git = "https://github.com/paritytech/substrate" }
state_machine = { package = "substrate-state-machine", git = "https://github.com/paritytech/substrate" }
substrate-executor = { git = "https://github.com/paritytech/substrate" }
primitives = { package = "substrate-primitives",git = "https://github.com/paritytech/substrate" }
trie = { package = "substrate-trie", git = "https://github.com/paritytech/substrate" }
node-primitives = { path = "../primitives" }
node-runtime = { path = "../runtime" }

[dev-dependencies]
keyring = { package = "substrate-keyring",git = "https://github.com/paritytech/substrate" }
runtime_primitives = { package = "sr-primitives",git = "https://github.com/paritytech/substrate" }
runtime_support = { package = "srml-support", git = "https://github.com/paritytech/substrate" }
balances = { package = "srml-balances", git = "https://github.com/paritytech/substrate" }
session = { package = "srml-session", git = "https://github.com/paritytech/substrate" }
#staking = { package = "srml-staking", git = "https://github.com/paritytech/substrate"}
system = { package = "srml-system", git = "https://github.com/paritytech/substrate" }
consensus = { package = "srml-consensus", git = "https://github.com/paritytech/substrate" }
timestamp = { package = "srml-timestamp", git = "https://github.com/paritytech/substrate" }
treasury = { package = "srml-treasury", git = "https://github.com/paritytech/substrate"}
contract = { package = "srml-contract", git = "https://github.com/paritytech/substrate" }
grandpa = { package = "srml-grandpa", git = "https://github.com/paritytech/substrate" }
indices = { package = "srml-indices", git = "https://github.com/paritytech/substrate" }
wabt = "~0.7.4"

staking = { package = "srml-staking", path = "../ladderml/staking"}

[features]
benchmarks = []
